# -*- coding: utf-8 -*-
"""wine_type_predictor_deployment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eu5U--29718S2HYpsfGr8WHKkH9fmeHE
"""

import streamlit as st
import pandas as pd
import joblib

fixed_acidity = st.number_input("Fixed Acidity")
volatile_acidity = st.number_input("Volatile Acidity")
citric_acid = st.number_input("Citric Acid")
residual_sugar = st.number_input("Residual Sugar")
cholorides = st.number_input("Cholorides")
free_sulfur_dioxide = st.number_input("Free Sulphur Dioxide")
total_sulfur_dioxide = st.number_input("Total Sulphur Dioxide")
density = st.number_input("Density")
pH = st.number_input("pH")
sulphates = st.number_input("Sulphates")
alcohol = st.number_input("Alcohol")
quality = st.number_input("Quality")

df = pd.DataFrame({
    'fixed_acidity': [fixed_acidity],
    'volatile_acidity': [volatile_acidity],
    'citric_acid': [citric_acid],
    'residual_sugar': [residual_sugar],
    'chlorides': [cholorides],
    'free_sulfur_dioxide': [free_sulfur_dioxide],
    'total_sulfur_dioxide': [total_sulfur_dioxide],
    'density': [density],
    'pH': [pH],
    'sulphates': [sulphates],
    'alcohol': [alcohol],
    'quality': [quality]
})

if st.button('Predict'):
    model = joblib.load('wine_type_prediction.pkl')
    prediction = wine_type_prediction.predict(df)[0]
    if prediction == 0:
        prediction = 'red Wine'
    else:
        prediction = 'white Wine'
    st.write(prediction)
